Completed listing form, added post request functionality
PentaLam/HomemadeGoods pull request #29
Opened 2020-11-07 23:58 UTC by arturob1024

2020-11-08 00:00 UTC, arturob1024 commented
I renamed listingPage to listingForm because it's a component not a page. When the merge occurs, git might not remove listingPage. Have to remove in future commit.

2020-11-12 06:07 UTC, LamLieu requested changes
Overall looks good, just a few fixes/additions.

2020-11-12 06:07 UTC, LamLieu commented on controllers/listings.js
> +    console.log("bazinga");
Change console log message so the others would know that a listing was added.

2020-11-12 06:07 UTC, LamLieu commented on client/debug.log
> +[1107/124554.112:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Add this file to .gitignore file

2020-11-12 06:11 UTC, LamLieu commented
> I renamed listingPage to listingForm because it's a component not a page. When the merge occurs, git might not remove listingPage. Have to remove in future commit.

If you look at the "Files changed" tab, you will see that "FormPage" was removed and "listingForm" was added. The merge will be ok! 👍

2020-11-15 08:06 UTC, LamLieu approved these changes

2020-11-15 08:07 UTC, merged